### ISSUE TITLE
`build --with` command fails with panic

### ISSUE THREAD

**Issue by whilei** [caddyserver/xcaddy#107]
I was trying to build with https://caddyserver.com/docs/modules/http.handlers.rate_limit.

```
uname -a && go version
Linux ubp52 5.2.9-050209-generic #201908160940 SMP Fri Aug 16 09:42:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
go version go1.17.8 linux/amd64

xcaddy version
v0.3.0 h1:3LTHAhHb5YKKqTLLj8kdF9cfGMl4jHV4uRbtw7LBJ6k=

```

```
xcaddy build --with github.com/mholt/caddy-ratelimit

[...]

go: downloading github.com/felixge/httpsnoop v1.0.2
go: downloading go.opentelemetry.io/otel/metric v0.27.0
go: downloading go.opentelemetry.io/otel/trace v1.4.0
go: downloading github.com/go-logr/logr v1.2.2
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading go.opentelemetry.io/otel/exporters/otlp v0.20.0
go: downloading go.opentelemetry.io/otel/internal/metric v0.27.0
go: downloading go.opentelemetry.io/proto/otlp v0.12.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.4.0
go: downloading github.com/cenkalti/backoff/v4 v4.1.2
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
2022/07/12 09:45:07 [INFO] Build environment ready
2022/07/12 09:45:07 [INFO] Building Caddy
2022/07/12 09:45:07 [INFO] exec (timeout=0s): /home/ia/go1.17.8.linux-amd64/bin/go mod tidy 
go: downloading go.uber.org/goleak v1.1.12
go: downloading github.com/golang/mock v1.6.0
go: downloading github.com/onsi/gomega v1.13.0
go: downloading github.com/smallstep/assert v0.0.0-20200723003110-82e2b9b3b262
go: downloading github.com/benbjohnson/clock v1.1.0
go: downloading github.com/cockroachdb/apd v1.1.0
go: downloading github.com/gofrs/uuid v4.0.0+incompatible
go: downloading github.com/aws/aws-sdk-go v1.37.0
go: downloading cloud.google.com/go/kms v1.4.0
go: downloading github.com/googleapis/gax-go/v2 v2.1.1
go: downloading google.golang.org/api v0.70.0
go: downloading github.com/chzyer/test v0.0.0-20180213035817-a1ea475d72b1
go: downloading github.com/jackc/pgmock v0.0.0-20210724152146-4ad1a8207f65
go: downloading github.com/lib/pq v1.10.2
go: downloading cloud.google.com/go v0.100.2
go: downloading github.com/OneOfOne/xxhash v1.2.2
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/chzyer/logex v1.1.10
go: downloading cloud.google.com/go/iam v0.1.0
go: downloading golang.org/x/oauth2 v0.0.0-20220223155221-ee480838109b
go: downloading cloud.google.com/go/compute v1.3.0
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/Masterminds/sprig v2.22.0+incompatible
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/jackc/pgproto3 v1.1.0
go: downloading github.com/jackc/chunkreader v1.0.0
2022/07/12 09:45:15 [INFO] exec (timeout=0s): /home/ia/go1.17.8.linux-amd64/bin/go build -o /home/ia/caddy -ldflags -w -s -trimpath 
# mime
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaacc42]

goroutine 1 [running]:
cmd/compile/internal/staticinit.(*Schedule).addvalue(0xc0000cfad0, 0xc000128450, 0x0, {0xe4cf28, 0xc000628600})
        /usr/local/go/src/cmd/compile/internal/staticinit/sched.go:443 +0x162
cmd/compile/internal/staticinit.(*Schedule).initplan(0xc0000cfad0, {0xe4ce60, 0xc0004c2f00})
        /usr/local/go/src/cmd/compile/internal/staticinit/sched.go:395 +0x367
cmd/compile/internal/staticinit.(*Schedule).StaticAssign(0xc0000cfad0, 0xc0004e9450, 0x0, {0xe4ce60, 0xc0004c2f00}, 0xc00061caf0)
        /usr/local/go/src/cmd/compile/internal/staticinit/sched.go:269 +0x15e
cmd/compile/internal/staticinit.(*Schedule).tryStaticInit(0x4036d6, {0xe4c690, 0xc0004f1e50})
        /usr/local/go/src/cmd/compile/internal/staticinit/sched.go:76 +0x13f
cmd/compile/internal/staticinit.(*Schedule).StaticInit(0xc0000cfad0, {0xe4c690, 0xc0004f1e50})
        /usr/local/go/src/cmd/compile/internal/staticinit/sched.go:49 +0x31
cmd/compile/internal/pkginit.(*InitOrder).flushReady(0xc0003edcb0, 0xc0000cfaa8)
        /usr/local/go/src/cmd/compile/internal/pkginit/initorder.go:167 +0x1ca
cmd/compile/internal/pkginit.initOrder({0xc0004cc700, 0x41, 0x1a})
        /usr/local/go/src/cmd/compile/internal/pkginit/initorder.go:95 +0x405
cmd/compile/internal/pkginit.Task()
        /usr/local/go/src/cmd/compile/internal/pkginit/init.go:24 +0x45
cmd/compile/internal/gc.Main(0xd16700)
        /usr/local/go/src/cmd/compile/internal/gc/main.go:197 +0xb38
main.main()
        /usr/local/go/src/cmd/compile/main.go:55 +0xdd
2022/07/12 09:45:31 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-07-12-0944.750050962
2022/07/12 09:45:31 [FATAL] exit status 2

```

**Comment by whilei** [comment]
... but then re-running the command apparently fixed it.


```
xcaddy build --with github.com/mholt/caddy-ratelimit
2022/07/12 09:48:25 [INFO] Temporary folder: /tmp/buildenv_2022-07-12-0948.3167600309
2022/07/12 09:48:25 [INFO] Writing main module: /tmp/buildenv_2022-07-12-0948.3167600309/main.go
package main

import (
        caddycmd "github.com/caddyserver/caddy/v2/cmd"

        // plug in Caddy modules here
        _ "github.com/caddyserver/caddy/v2/modules/standard"
        _ "github.com/mholt/caddy-ratelimit"
)

func main() {
        caddycmd.Main()
}
2022/07/12 09:48:25 [INFO] Initializing Go module
2022/07/12 09:48:25 [INFO] exec (timeout=10s): /home/ia/go1.17.8.linux-amd64/bin/go mod init caddy 
go: creating new go.mod: module caddy
go: to add module requirements and sums:
        go mod tidy
2022/07/12 09:48:25 [INFO] Pinning versions
2022/07/12 09:48:25 [INFO] exec (timeout=0s): /home/ia/go1.17.8.linux-amd64/bin/go get -d -v github.com/caddyserver/caddy/v2 
go get: added github.com/beorn7/perks v1.0.1
go get: added github.com/caddyserver/caddy/v2 v2.5.1
go get: added github.com/caddyserver/certmagic v0.16.1
go get: added github.com/cespare/xxhash/v2 v2.1.2
go get: added github.com/cheekybits/genny v1.0.0
go get: added github.com/fsnotify/fsnotify v1.5.1
go get: added github.com/go-task/slim-sprig v0.0.0-20210107165309-348f09dbbbc0
go get: added github.com/golang/protobuf v1.5.2
go get: added github.com/google/uuid v1.3.0
go get: added github.com/klauspost/cpuid/v2 v2.0.11
go get: added github.com/libdns/libdns v0.2.1
go get: added github.com/lucas-clemente/quic-go v0.26.0
go get: added github.com/marten-seemann/qpack v0.2.1
go get: added github.com/marten-seemann/qtls-go1-16 v0.1.5
go get: added github.com/marten-seemann/qtls-go1-17 v0.1.1
go get: added github.com/marten-seemann/qtls-go1-18 v0.1.1
go get: added github.com/matttproud/golang_protobuf_extensions v1.0.1
go get: added github.com/mholt/acmez v1.0.2
go get: added github.com/miekg/dns v1.1.46
go get: added github.com/nxadm/tail v1.4.8
go get: added github.com/onsi/ginkgo v1.16.4
go get: added github.com/prometheus/client_golang v1.12.1
go get: added github.com/prometheus/client_model v0.2.0
go get: added github.com/prometheus/common v0.32.1
go get: added github.com/prometheus/procfs v0.7.3
go get: added go.uber.org/atomic v1.9.0
go get: added go.uber.org/multierr v1.6.0
go get: added go.uber.org/zap v1.21.0
go get: added golang.org/x/crypto v0.0.0-20220210151621-f4118a5b28e2
go get: added golang.org/x/mod v0.4.2
go get: added golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd
go get: added golang.org/x/sys v0.0.0-20220209214540-3681064d5158
go get: added golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go get: added golang.org/x/text v0.3.8-0.20211004125949-5bd84dd9b33b
go get: added golang.org/x/tools v0.1.7
go get: added golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go get: added google.golang.org/protobuf v1.27.1
go get: added gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
2022/07/12 09:48:25 [INFO] exec (timeout=0s): /home/ia/go1.17.8.linux-amd64/bin/go get -d -v github.com/mholt/caddy-ratelimit github.com/caddyserver/caddy/v2 
go get: upgraded github.com/fsnotify/fsnotify v1.5.1 => v1.5.4
go get: upgraded github.com/go-logfmt/logfmt v0.5.0 => v0.5.1
go get: upgraded github.com/klauspost/cpuid/v2 v2.0.11 => v2.0.12
go get: added github.com/mholt/caddy-ratelimit v0.0.0-20220428144044-9c011f665e5d
go get: upgraded github.com/miekg/dns v1.1.46 => v1.1.48
go get: upgraded github.com/onsi/ginkgo v1.16.4 => v1.16.5
go get: upgraded github.com/prometheus/common v0.32.1 => v0.34.0
go get: upgraded go.uber.org/multierr v1.6.0 => v1.8.0
go get: upgraded golang.org/x/crypto v0.0.0-20220210151621-f4118a5b28e2 => v0.0.0-20220411220226-7b82a4e95df4
go get: upgraded golang.org/x/mod v0.4.2 => v0.6.0-dev.0.20220106191415-9b9b3d81d5e3
go get: upgraded golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd => v0.0.0-20220425223048-2871e0cb64e4
go get: upgraded golang.org/x/sys v0.0.0-20220209214540-3681064d5158 => v0.0.0-20220422013727-9388b58f7150
go get: upgraded golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 => v0.0.0-20220411215600-e5f449aeb171
go get: upgraded golang.org/x/tools v0.1.7 => v0.1.10
go get: upgraded golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 => v0.0.0-20220411194840-2f41105eb62f
go get: upgraded google.golang.org/protobuf v1.27.1 => v1.28.0
2022/07/12 09:48:27 [INFO] exec (timeout=0s): /home/ia/go1.17.8.linux-amd64/bin/go get -d -v  
2022/07/12 09:48:28 [INFO] Build environment ready
2022/07/12 09:48:28 [INFO] Building Caddy
2022/07/12 09:48:28 [INFO] exec (timeout=0s): /home/ia/go1.17.8.linux-amd64/bin/go mod tidy 
2022/07/12 09:48:28 [INFO] exec (timeout=0s): /home/ia/go1.17.8.linux-amd64/bin/go build -o /home/ia/caddy -ldflags -w -s -trimpath 
2022/07/12 09:48:35 [INFO] Build complete: ./caddy
2022/07/12 09:48:35 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-07-12-0948.3167600309

echo $?
0

```

**Comment by mholt** [comment]
Weird, that panic is in the Go compiler.

I would file an issue upstream in the [Go project](https://github.com/golang/go). :thinking:

**Comment by francislavoie** [comment]
Looks like you're using Go 1.17, try with Go 1.18.
