### ISSUE TITLE
xcaddy build: fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by ThukuWakogi** [caddyserver/xcaddy#56]
Following [this guide](https://www.digitalocean.com/community/tutorials/how-to-host-a-website-with-caddy-on-ubuntu-18-04), I'm attempting to install caddy on ubuntu server 18.04.

The build fails with `fatal error: runtime: out of memory`

This is the build output when running `xcaddy build`.
```
2021/03/11 10:21:30 [INFO] Temporary folder: /tmp/buildenv_2021-03-11-1021.749880544
2021/03/11 10:21:30 [INFO] Writing main module: /tmp/buildenv_2021-03-11-1021.749880544/main.go
2021/03/11 10:21:30 [INFO] Initializing Go module
2021/03/11 10:21:30 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy
go: creating new go.mod: module caddy
go: to add module requirements and sums:
        go mod tidy
2021/03/11 10:21:30 [INFO] Pinning versions
2021/03/11 10:21:30 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2
go get: added github.com/caddyserver/caddy/v2 v2.3.0
2021/03/11 10:21:36 [INFO] Build environment ready
2021/03/11 10:21:36 [INFO] Building Caddy
2021/03/11 10:21:36 [INFO] exec (timeout=0s): /usr/local/go/bin/go mod tidy
2021/03/11 10:21:39 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /home/test_user/caddy/caddy -ldflags -w -s -trimpath
# github.com/yuin/goldmark/util
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xcac687, 0x16)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc010000000, 0x4000000, 0x11e7b90)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x11c8bc0, 0x400000, 0x42bcf7, 0x11c8bc8)
        /usr/local/go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x11c8bc0, 0x20, 0x0)
        /usr/local/go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x11c8bc0, 0x20, 0x460000, 0x7fcaf6837928)
        /usr/local/go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x46d334)
        /usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1246

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc00aa33468 sp=0xc00aa33460 pc=0x46d460
runtime.(*mheap).alloc(0x11c8bc0, 0x20, 0x200100, 0x203003)
        /usr/local/go/src/runtime/mheap.go:904 +0x85 fp=0xc00aa334b8 sp=0xc00aa33468 pc=0x4279a5
runtime.(*mcache).allocLarge(0x7fcb1d9fd108, 0x3e590, 0x30001, 0xc8e5e0)
        /usr/local/go/src/runtime/mcache.go:224 +0x97 fp=0xc00aa33510 sp=0xc00aa334b8 pc=0x418017
runtime.mallocgc(0x3e590, 0xc8e5e0, 0xcc8b01, 0x1)
        /usr/local/go/src/runtime/malloc.go:1078 +0x925 fp=0xc00aa33598 sp=0xc00aa33510 pc=0x40de65
runtime.makeslice(0xc8e5e0, 0x7cb2, 0x7cb2, 0xc0051070e8)
        /usr/local/go/src/runtime/slice.go:98 +0x6c fp=0xc00aa335c8 sp=0xc00aa33598 pc=0x44faec
cmd/compile/internal/ssa.fuseBlockPlain(0xc005106dc0, 0xc0029c0d00)
        /usr/local/go/src/cmd/compile/internal/ssa/fuse.go:209 +0x4bf fp=0xc00aa33668 sp=0xc00aa335c8 pc=0x688ebf
cmd/compile/internal/ssa.fuse(0xc0018ce2c0, 0x118469aa82505)
        /usr/local/go/src/cmd/compile/internal/ssa/fuse.go:40 +0xb3 fp=0xc00aa336a0 sp=0xc00aa33668 pc=0x6880f3
cmd/compile/internal/ssa.fuseEarly(0xc0018ce2c0)
        /usr/local/go/src/cmd/compile/internal/ssa/fuse.go:12 +0x30 fp=0xc00aa336c0 sp=0xc00aa336a0 pc=0x687fb0
cmd/compile/internal/ssa.Compile(0xc0018ce2c0)
        /usr/local/go/src/cmd/compile/internal/ssa/compile.go:96 +0x98d fp=0xc00aa37388 sp=0xc00aa336c0 pc=0x66086d
cmd/compile/internal/gc.buildssa(0xc000f358c0, 0x0, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/ssa.go:470 +0x11ba fp=0xc00aa375b0 sp=0xc00aa37388 pc=0xb0bc5a
cmd/compile/internal/gc.compileSSA(0xc000f358c0, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:319 +0x5d fp=0xc00aa37690 sp=0xc00aa375b0 pc=0xad733d
cmd/compile/internal/gc.compile(0xc000f358c0)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:277 +0x39e fp=0xc00aa37708 sp=0xc00aa37690 pc=0xad711e
cmd/compile/internal/gc.funccompile(0xc000f358c0)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:220 +0xc5 fp=0xc00aa37760 sp=0xc00aa37708 pc=0xad6c65
cmd/compile/internal/gc.Main(0xcc7d28)
        /usr/local/go/src/cmd/compile/internal/gc/main.go:762 +0x3525 fp=0xc00aa37f10 sp=0xc00aa37760 pc=0xaabbe5
main.main()
        /usr/local/go/src/cmd/compile/main.go:52 +0xb1 fp=0xc00aa37f88 sp=0xc00aa37f10 pc=0xbf90d1
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc00aa37fe0 sp=0xc00aa37f88 pc=0x439d76
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00aa37fe8 sp=0xc00aa37fe0 pc=0x46f161
2021/03/11 10:21:46 [INFO] Cleaning up temporary folder: /tmp/buildenv_2021-03-11-1021.749880544
2021/03/11 10:21:46 [FATAL] exit status 2
```

**Comment by francislavoie** [comment]
How much RAM does your machine have?

**Comment by ThukuWakogi** [comment]
1GB
Its a digitalocean server.

after running `free -h --si`
```
              total        used        free      shared  buff/cache   available
Mem:           1.0G        541M        361M         14M        106M        335M
Swap:            0B          0B          0B
```

**Comment by francislavoie** [comment]
You'd probably be better off building on your local machine then copying the binary to your server. Golang can cross-compile by using environment variables https://caddyserver.com/docs/build#cross-platform

**Comment by francislavoie** [comment]
FWIW, I find that guide you linked to be pretty overly complicated. My recommendation would be to instead install Caddy using our cloudsmith repo, which sets up the systemd service and other accompanying files https://caddyserver.com/docs/install#debian-ubuntu-raspbian and then follow these instructions to maintain your custom build https://github.com/caddyserver/website/pull/141/files?short_path=020f9b6#diff-020f9b6f3fa4b829965ac68e40dd3974c83d8c0e52e5ee499f3f8c690fde227d

It seems like you're using a stock build of Caddy though (i.e. no plugins added to Caddy), in which case that entire guide is made redundant by just installing the apt repo we provide (you don't need to build Caddy yourself).

**Comment by ThukuWakogi** [comment]
Installation was successful using the cloudsmith repo. I grateful for your help.
